ci:
  autofix_prs: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      # https://github.com/pre-commit/pre-commit-hooks/issues/718
      # - id: check-added-large-files  # Fails with git v1.8.3
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: (requirements.txt)$
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: "22.10.0"
    hooks:
      - id: black
      - id: black-jupyter

  - repo: https://github.com/PyCQA/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/isort
    rev: "5.10.1"
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.991"
    hooks:
      - id: mypy
        additional_dependencies:
        - types-pkg_resources

  - repo: https://github.com/PyCQA/pydocstyle
    rev: "6.1.1"
    hooks:
      - id: pydocstyle
        additional_dependencies: [toml]
        exclude: test
